DATE_PICKER = 'date-picker'
DATE_PICKER_DIV = 'date-picker-div'
TABLE_CONTAINER = 'table-container'
UPDATE_TABLE = 'update-table'
TABLE_FAST_RANGE = 'table-date-items'
WARNING_CONTAINER = 'update-warning'
EXCEL_DOWNLOAD_BUTTON = 'excel-download-button'
HTML_DOWNLOAD_BUTTON = 'html-download-button'
PDF_DOWNLOAD_BUTTON = 'pdf-download-button'
TABLE_DOWNLOAD = 'table-download'
LANGUAGE_DROPDOWN = 'language-dropdown'
UPLOAD_DATA = 'upload-data'
UPLOAD_SUCESS = 'upload-success'
UPLOAD_DATA_BADGE = 'upload-data-badge'

